name: Deploy Project
on: push # 푸시 할 때 마다
jobs:
    test: # 이름
        runs-on: ubuntu-latest # 우분투 쓰면 node는 자동으로 설치
        steps:
            - name:
                  Get code # 깃허브 서버가 코드를 가져와야함
                  # uses는 외부 액션을 실행하기 위해 사용되는 키워드
              uses:
                  actions/checkout@v3 # 현재 브랜치의 코드를 다운로드하여 작업 공간에 배치해줌
                  # with:
            - name: Install NodeJS # 우분투는 이미 있지만 그래도 설치하고 싶다면
              uses: actions/setup-node@v3
              with: # with는 추가 구성
                  node-version: 18
            - name: Install dependencies
              run: npm ci # package-lock.json 기반으로 설치
            - name: Run tests
              run: npm test
    # 두번째 jobs - 독립적이므로 서로에게 영향을 주지 않는다(병렬 실행)
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Deploy
              run: echo "배포 예시....."
